# Generated by Django 5.1.3 on 2024-11-29 04:41

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campusApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='universitycampus',
            options={'verbose_name_plural': 'University Campus'},
        ),
        migrations.AlterModelManagers(
            name='universitycampus',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
